BEGIN {
  inheader=0;
  print "/*! \\file  " name
  print " *"
  print " *  \\brief Function decoration for the Matterflow package"
  print " *"
  print " *---------------------------------------------------------------------------------"
  print " *  Copyright (C) 2021-2022 by the CAEP-XTU team. All rights reserved.             "
  print " *---------------------------------------------------------------------------------"
  print " *"
  print " *  \\warning DO NOT EDIT!!! This file is automatically generated!"
  print " */ \n"

  print "#include \"matterflow.h\" "
}

{
  if (inheader) {
    if (match($0,"[)][ \t]*$")) {
      inheader = 0;
      printf "%s;\n\n",$0;
    } else {
      printf "%s\n",$0;
    }
    next;
  }
}

/\/*! \\file/ {
    printf "\n/*-------- In file: %s --------*/\n\n",$3;  
}

/^inline|^static|^extern/ || !/^[a-zA-Z]/ || /[;]/ {
  next;
}

!/^INT|^SHORT|^LONG|^REAL|^FILE|^OFF_T|^size_t|^off_t|^pid_t|^unsigned|^mode_t|^DIR|^idx_t|^user|^int|^short|^long|^char|^uint|^struct|^bool|^void|^double|^vec2D|^tensor2D|^Triangle|^Vertex/ {
  next;
}

/[(].*[)][ \t]*$/ {
    printf "%s;\n\n",$0;
    next;
}

/[(]/ {
  inheader=1;
  printf "%s\n",$0;
  next;
}

END {
  print "/* End of " name " */"
}
